export const READ_FILES = "READ_FILES";
export const READ_ONE_FILE = "READ_ONE_FILE";
export const CREATE_FILE = "CREATE_FILE";
export const FILE_ERROR = "FILE_ERROR";
export const START_FILES_RELOAD = "START_FILES_RELOAD";
export const FINISHED_FILES_RELOAD = "FINISHED_FILES_RELOAD";
