export const READ_SCHEDULED_WASHES = 'READ_SCHEDULED_WASHES';
export const READ_ONE_SCHEDULED_WASH = 'READ_ONE_SCHEDULED_WASH';
export const CREATE_SCHEDULED_WASH = 'CREATE_SCHEDULED_WASH';
export const UPDATE_SCHEDULED_WASH = 'UPDATE_SCHEDULED_WASH';
export const UPDATE_SCHEDULED_WASH_STATUS = 'UPDATE_SCHEDULED_WASH_STATUS';

export const DELETE_SCHEDULED_WASH = 'DELETE_SCHEDULED_WASH';
export const SEARCH_SCHEDULED_WASH_FILTER = 'SEARCH_SCHEDULED_WASH_FILTER';
export const SCHEDULED_WASH_ERROR = 'SCHEDULED_WASH_ERROR';
export const CLEAR_SCHEDULED_WASH = 'CLEAR_SCHEDULED_WASH';
export const START_SCHEDULED_WASHES_RELOAD = 'START_SCHEDULED_WASHES_RELOAD';
export const FINISHED_SCHEDULED_WASHES_RELOAD =
  'FINISHED_SCHEDULED_WASHES_RELOAD';
